### ISSUE TITLE
Write a C programme to find volume of sphere

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-programme#1025]
### Description

Write a programme to find volume of sphere

Volume of sphere = (4/3) * π * (radius)^3

```
Input  : 1
Output : 4.18879
```

**Comment by SpirosArk** [comment]
Isn't this already done? https://github.com/codinasion/codinasion-programme/blob/master/programme/volume-of-sphere/volume-of-sphere.c
