### ISSUE TITLE
Degree to radian

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-programme#1166]
### Description

Write a programme to convert degree to radian

1Deg × π/180 = 0.01745Rad

```
Input  : 1
Output : 0.0174533
```

### Tracking Issues

- [x] #1167
- [x] #1168
- [x] #1169
- [x] #1170
- [x] #1171
- [x] #1172
- [x] #1173
- [x] #1174
- [x] #1175

**Comment by SpirosArk** [comment]
9/9 in here https://github.com/codinasion/codinasion-programme/tree/master/programme/degree-to-radian
