### ISSUE TITLE
Radian to degree

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-programme#1176]
### Description

Write a programme to convert radian to degree

1Deg × π/180 = 0.01745Rad

```
Input  : 1
Output : 57.2958
```

### Tracking Issues

- [x] #1177
- [x] #1178
- [x] #1179
- [x] #1180
- [x] #1181
- [x] #1182
- [x] #1183
- [x] #1184
- [x] #1185

**Comment by SpirosArk** [comment]
All isuess are done and merged https://github.com/codinasion/codinasion-programme/tree/master/programme/radian-to-degree
