### ISSUE TITLE
Add support for rust.

### ISSUE THREAD

**Issue by GodKimba** [codinasion/codinasion-programme#1232]
### Description

I'm almost finishing the Rust Book and i feel that i can contribute to the project. Is this of interest for the project? 

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
ok course @GodKimba , you can contribute to any programme 👍🏻
