### ISSUE TITLE
Pull #1247 must be revoked, code on pull #1247 solves Issue #1117 instead of Issue #1097, Issue #1117 must be closed and Issue #1097 must reopen

### ISSUE THREAD

**Issue by SpirosArk** [codinasion/codinasion-programme#1252]
### What would you like to share?

I was running up some tests for the code I submitted. 

I ended up on issue #1117  and when I was about to implement it I realized that it's the same code that was merged on pull #1247 . My program that I committed on #1247 does not check whether or not the output number is divisible by any other number. The output is just odd. So the commit that fixes issue #1117 is in pull #1247 and issue #1097 should be opened again.

**Comment by harshraj8843** [comment]
Hey @SpirosArk 

the code submitted in #1247 

```c
(rand() % (upper - lower + 1)) + lower)
```

generate random number (even and odd both) that's why it closes the issue #1097 , I may misunderstood that but I didn't know why to reopen that issue

**Comment by harshraj8843** [comment]
> code on pull https://github.com/codinasion/codinasion-programme/issues/1247 solves Issue https://github.com/codinasion/codinasion-programme/issues/1117

code on pull #1247 solves Issue #1097

**Comment by SpirosArk** [comment]
Sorry, Pull #1250 not #1247

**Comment by SpirosArk** [comment]
random-prime-number.c on Pull #1250 solves issue #1117 
issue #1127 must reopen
