### ISSUE TITLE
random-prime-number.c on Pull #1250 solves issue #1117

### ISSUE THREAD

**Issue by SpirosArk** [codinasion/codinasion-programme#1254]
random-prime-number.c on Pull #1250 solves issue #1117 
issue #1127 must reopen

_Originally posted by @SpirosArk in https://github.com/codinasion/codinasion-programme/issues/1252#issuecomment-1192858808_

**Comment by harshraj8843** [comment]
Just some clarification 🤔 

---

> random-prime-number.c on Pull https://github.com/codinasion/codinasion-programme/pull/1250 solves issue https://github.com/codinasion/codinasion-programme/issues/1117

#1250 contains code for `count-capital-letters`, `random-number`, `random-prime-number`

But #1117 is for `random odd number`

How #1250 closes #1117

**Comment by SpirosArk** [comment]
random-prime-number does not check about whether the found number is divided by any other number.

So the output is always an odd number that does not checked whether it is prime or not. 

All prime numbers are odd, but not all odd numbers are prime. 
We miss the check on random-prime-number.

**Comment by Greenboat24** [comment]
>All prime numbers are odd, but not all odd numbers are prime.

2 is prime.

**Comment by SpirosArk** [comment]
Yeah, was referring to the logic that `random-prime-number.c` is executing.

**Comment by harshraj8843** [comment]
Maybe done, please check 👍🏻
