### ISSUE TITLE
Area of a trapezoid

### ISSUE THREAD

**Issue by yougottawork** [codinasion/codinasion-programme#496]
### Description

Write a program that:

* Takes the length of two bases and height
* Uses the formula to calculate the area
* Return the area

Area of a trapezoid = ( ` base 1 ` + ` base 2 ` ) * ` height ` / 2

#### Example:

Base 1 = 5, Base 2 = 10, Height = 7

Area of the trapezoid = (5+10)*7/2 = 52.5

#### Programme

```
Base 1 : 5
Base 2 : 10
Height  : 7

Area : 52.5
```

### Tracking Issues

- [x] #498
- [x] #499
- [x] #500
- [x] #501
- [x] #502
- [x] #731
- [x] #732

**Comment by harshraj8843** [comment]
Hey @yougottawork 

Thanks for opening this Issue 👍🏻
