### ISSUE TITLE
Area of a rhombus

### ISSUE THREAD

**Issue by yougottawork** [codinasion/codinasion-programme#505]
### Title of article

Write a program to compute area of Rhombus

- Takes the length of **two diagonals**
- Uses the formula to calculate the area
- Return the value

Area of a rhombus = ( ` diagonal 1 ` * ` diagonal 2 ` ) / 2

#### Example:

Diagonal 1 = 6, Diagonal 2 = 8

Area of the rhombus = (6*8)/2 = 24

#### Programme

```
Diagonal 1 : 6
Diagonal 2 : 8

Area : 24
```

### Tracking Issues

- [x] #508 
- [x] #509 
- [x] #510 
- [x] #511 
- [x] #512 
- [x] #733
- [x] #734

**Comment by lt77777** [comment]
I can do this!
