### ISSUE TITLE
Volume of a cylinder

### ISSUE THREAD

**Issue by yougottawork** [codinasion/codinasion-programme#522]
### Title of article

Write a program to compute the **volume** of the **Cylinder**

- Takes the length of **radius and height**
- Uses the formula to calculate the volume
- Return the value

Volume of a cylinder = ` radius ` * ` radius ` * ` height ` * ` π `

#### Example:

radius = 8, height = 10

Volume of a cylinder = 8 * 8 * 10 * π = 2010.62 (round to 2 decimal places)

#### Programme

```
Radius : 8
Height : 10

Volume : 2010.62
```

### Tracking Issues

- [x] #526 
- [x] #527 
- [x] #528 
- [x] #529 
- [x] #530

**Comment by harshraj8843** [comment]
Hey @yougottawork 

Thanks for opening this Issue 👍🏻
