### ISSUE TITLE
Name of class must match filename

### ISSUE THREAD

**Issue by Anzo52** [codinasion/codinasion-programme#531]
### What would you like to share?

https://github.com/codinasion/codinasion-programme/blob/6fb2c99d4720f9fca06ddd57acca96059a4ad2d5/programme/years-to-days/years-to-days.java#L4

this line must be changed to:

`public class years-to-days {`

### Additional information

I can fix and do a PR if needed.

**Comment by harshraj8843** [comment]
Well for now, we are ignoring that issue.

We will update all java file in a single PR soon.

We are going to have some major update very soon 😄 (work on progress)

Thanks for noticing 👍🏻

**Comment by Anzo52** [comment]
Actuallly, this won't be permitted in Java (the dashes, that is). It breaks stuff. 😂

**Comment by harshraj8843** [comment]
> Actuallly, this won't be permitted in Java (the dashes, that is). It breaks stuff. joy

You can create a PR for this, if you want 👍🏻 

You can also fix other `java` files having this issue

**Comment by harshraj8843** [comment]
> We are going to have some update very soon smile (work on progress)

#549 

Join the discussion :-  

- to provide your valuable feedback
- to report any bug found
- to suggest new features
- and more...

Thanks 💖
