### ISSUE TITLE
Volume of a sphere

### ISSUE THREAD

**Issue by yougottawork** [codinasion/codinasion-programme#533]
### Title of article

Write a program to compute the **volume** of the **Sphere**

Takes the length of **radius**
Uses the formula to calculate the volume
Return the value

Volume of a sphere = ` radius ` * ` radius ` * ` radius `  * ` 4/3 `  * ` π `

#### Example:

radius = 8

Volume of a sphere = 8^3 * π * 4/3 = 2144.66 (round to 2 decimal places)

#### Programme:

```
Radius : 8

Volume : 2144.66
```

### Tracking Issues

- [x] #539 
- [x] #540 
- [x] #541 
- [x] #542 
- [x] #543

**Comment by aashish-khub** [comment]
Could I claim this issue?

**Comment by harshraj8843** [comment]
Hey @aashish-khub 

Thanks for showing your interest in this project 😃 

This issue has been updated, you can choose issue of a particular language and raise a PR for that.

- #539 C
- #540 C++
- #541 C#
- #542 Java
- #543 Python

Thanks
