### ISSUE TITLE
v3-beta

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-programme#550]
### v3-beta

We are migrating [Codinasion](https://codinasion.web.app/) site from [Gatsby Js](https://www.gatsbyjs.com/) to [Next Js](https://nextjs.org/)

Programme Demo :- [codinasion.vercel.app/programme](https://codinasion.vercel.app/programme)

Join Discussion #549 

- Give feedback
- Report Bug
- Suggest Features
- and more...

**Comment by GodKimba** [comment]
Hey, harshraj! I'm getting familiar with golang and I'm down to recreate the preexisting tutorials for it. Let me know if that interest you!

**Comment by harshraj8843** [comment]
> Hey, harshraj! I'm getting familiar with golang and I'm down to recreate the preexisting tutorials for it. Let me know if that interest you!

Sorry, i didn't get it 🤔

**Comment by GodKimba** [comment]
No problem! I didn't made myself clear, I can code tutorials like: minutes to hours, square of a triangle, etc.  in Golang and send the pull request for you to add it in the website/repo. If that is in your interest, of course. English isn't my first language so, sorry about that!

**Comment by harshraj8843** [comment]
> I can code tutorials like: minutes to hours, square of a triangle, etc. in Golang and send the pull request for you to add it in the website/repo

That would be great 👍🏻 

Thanks for showing your interest in this project 😃

**Comment by HaveACookie** [comment]
Have you considered adding JavaScript to the languages for solutions? It is a very popular language.

**Comment by harshraj8843** [comment]
> Have you considered adding JavaScript to the languages for solutions? It is a very popular language.

That is really a good idea 👍🏻 

Thanks
