### ISSUE TITLE
Issue in /programme/alphabet-triangle-pattern/README.md

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-programme#556]
### What article on codinasion.web.app is affected?

https://codinasion.web.app/programme/alphabet-triangle-pattern

### What part(s) of the article would you like to see updated?

Title should be `Alphabet triangle pattern` instead of `Number triangle pattern`

Description Should be `Write a program to print alphabet triangle pattern` instead of `Write a program to print number triangle pattern`

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

**Comment by shrionit** [comment]
Hey,
This is my first time contributing.
So please guide me.

**Comment by harshraj8843** [comment]
Hey @shrionit 

Thanks for showing your interest in this project 👍🏻 

<details>
<summary>Steps to solve this issue :-</summary>

- `fork` this repo
- `clone` the forked repo
- change title of the [`README.md` file](https://github.com/codinasion/codinasion-programme/blob/master/programme/alphabet-triangle-pattern/README.md) from `Number triangle pattern` to `Alphabet triangle pattern`
- `commit` and `push`
- open a `PR` (pull request)

</details>

If you are an absolute beginner to Github contributions, please consider [this repo](https://github.com/codinasion/first-pull-request)

You can contribute [here](https://github.com/codinasion/first-pull-request) first to get an idea about how Github contribution works

You can further ask for any clarification

**Comment by shrionit** [comment]
Should I change the description as well

**Comment by harshraj8843** [comment]
> Should I change the description as well

Sure 👍🏻

**Comment by shrionit** [comment]
It is done.
Please review the PR
