### ISSUE TITLE
Armstrong Number documentation and code is incorrect

### ISSUE THREAD

**Issue by Dentyr** [codinasion/codinasion-programme#655]
### Description

As stated in Wikipedia, including other sources:
(https://en.wikipedia.org/wiki/Narcissistic_number)
"In number theory, a narcissistic number (also known as a pluperfect digital invariant, an **Armstrong number**, or a plus perfect number) in a given number base b is a number that is the sum of its own digits each raised to the power of the number of digits."

Meanwhile, in the current documentation:
"Armstrong number is a number that is equal to the sum of cubes of its digits."

So in the python script, it says,
`while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10`

For Armstrong numbers which have 3 digits, this will be correct. However, for any other Armstrong numbers, like 1634, the program will incorrectly say that it is not an Armstrong number.

**Comment by harshraj8843** [comment]
Hey @Dentyr 

Thanks for noticing this issue 👍🏻 

This issue will be resolved soon

**Comment by siddhantchimankar** [comment]
Hey @harshraj8843 can I work on this issue?

**Comment by harshraj8843** [comment]
> Hey @harshraj8843 can I work on this issue?

Sure 👍🏻 

Steps to resolve this issue :- 
- update programme files in `programme/armstrong-number`
	- [ArmstrongNumber.java](https://github.com/codinasion/codinasion-programme/blob/master/programme/armstrong-number/ArmstrongNumber.java)
	- [armstrong-number.c](https://github.com/codinasion/codinasion-programme/blob/master/programme/armstrong-number/armstrong-number.c)
	- [armstrong-number.py](https://github.com/codinasion/codinasion-programme/blob/master/programme/armstrong-number/armstrong-number.py)
