### ISSUE TITLE
Change file name and class name to match naming conventions

### ISSUE THREAD

**Issue by Anzo52** [codinasion/codinasion-programme#701]
### What would you like to share?

Not urgent, 
According to Java naming conventions the class name is capitalized-camel-case (e.g. "CapitalizedCamelCase"), methods and functions are "regularCamelCase".

### Additional information

I can tackle renaming the Java files/classes again. Should I create a tracked issue?

**Comment by Anzo52** [comment]
https://github.com/codinasion/codinasion-programme/blob/7396aadcec170653838e253509c16b53a7f8a159/programme/area-of-rectangle/areaOfRectangle.java#L5

**Comment by harshraj8843** [comment]
> ### What would you like to share?
> Not urgent, According to Java naming conventions the class name is capitalized-camel-case (e.g. "CapitalizedCamelCase"), methods and functions are "regularCamelCase".
> 
> ### Additional information
> I can tackle renaming the Java files/classes again. Should I create a tracked issue?

Hey @Anzo52 

could you please raise a PR for this 👍🏻

**Comment by Anzo52** [comment]
Will be closed by PR #700

**Comment by harshraj8843** [comment]
> Will be closed by PR #700

Issues should not be closed before PR will be merged

**Comment by Anzo52** [comment]
> > Will be closed by PR #700
> 
> Issues should not be closed before PR will be merged

Sorry, messed up with git again. I confused myself. 😣

**Comment by harshraj8843** [comment]
> Sorry, messed up with git again. I confused myself. persevere

We all learn in the process 👍🏻
