### ISSUE TITLE
PHP Programmes

### ISSUE THREAD

**Issue by 0xRenegade** [codinasion/codinasion-programme#925]
### Title of programme

Write a PHP version of each Programme

### Additional information

Initially wrote this as a singular issue for one Programme for PHP, but figured a list of the remaining Programmes could be better (and less spam).

- [x] #931 
- [x] #932 
- [x] #933 
- [x] #934 
- [x] #935 
- [ ] Area of Trapezoid
- [ ] Armstrong Number
- [ ] ASCII Value
- [ ] Average of Numbers
- [ ] Celsius to Fahrenheit
- [ ] Check Leap Year
- [ ] Check Prime Number
- [ ] Compound Interest Calculator
- [ ] Decimal to Binary
- [ ] Digital Root
- [ ] Divide Two Numbers
- [ ] Euler Number
- [x] #1237
- [ ] Factorial
- [ ] Feet to Inches
- [ ] Fibonacci Pattern
- [ ] Fibonacci Series without Recursion
- [ ] Fibonacci Series with Recursion
- [ ] Harmonic Series
- [ ] Hello World
- [ ] Hours to Seconds
- [ ] Inches to Feet
- [ ] Length of String
- [ ] Matrix Multiplication
- [ ] Maximum of Numbers
- [ ] Merge Two Strings
- [ ] Minimum of Numbers
- [ ] Minutes to Seconds
- [ ] Multiplication Table
- [ ] Multiply Two Numbers
- [ ] Number to String
- [ ] Number Triangle Pattern
- [ ] Palindrome Number
- [ ] Pangram Checker
- [ ] Pattern 1, 2, 3
- [ ] Perimeter of Rectangle
- [ ] Perimeter of Square
- [ ] Print Even Numbers
- [ ] Reverse of a Number
- [ ] Rupee to Paise
- [ ] Simple Interest Calculator
- [ ] Square of Number
- [ ] Subtract Two Numbers
- [ ] Sum of Cubes
- [ ] Sum of Digits
- [ ] Sum of Square
- [ ] Swap Two Numbers
- [ ] Swap Two Numbers without Third Variable
- [ ] Volume of Cylinder
- [ ] Volume of Square
- [ ] X to the Power of Y
- [ ] Years to Days

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Hey @0xRenegade 

Thanks for making the list 👍🏻 

But, in my opinion individual issues are better, in the sense that individual issues can be linked to their respective PR(s)

Consider a situation that someone has raised a PR for `PHP` programme for `add-two-numbers`. That PR can be linked to the individual issue for the purpose. And when the PR will be merged, the respective issue will be closed automatically. So, there will be no situation of `spam`. The individual issues will be open until their respective PR(s) are not merge. And this situation helps others to find issues to contribute to, more easily.

On the other hand, in the situation you are proposing, we can not link a PR to this issue or for a particular programme in the list.

#### What to do now

You are welcome to create individual issues for the list 👍🏻 

<details>
<summary>If you consider opening the individual issues</summary>

<br>

Simply hover on the programme list above and click `Convert to Issue`

![Screenshot from 2022-06-26 10-18-00](https://user-images.githubusercontent.com/54644599/175799883-50f71ec8-6ef2-419e-9dc0-4235504581ec.png)

This will help us to track, which issues has been created 📝 

</details>

or, the respective issues will be created ASAP 😃 

Thanks 👍🏻
